export default {
  INIT_INGRDIENTS: "INIT_INGRDIENTS",
  INIT_INGRDIENTS_SUCCEDED: "INIT_INGRDIENTS_SUCCEDED",
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  UPDATE_PURCHASE: "UPDATE_PURCHASE",
};
